files:
  - source: /src/main/resources/ApplicationResources_en.properties
    translation: /src/main/resources/ApplicationResources_%two_letters_code%.properties
  - source: /docs/translations/index.pot
    translation: /docs/translations/%two_letters_code%.po
